### ISSUE TITLE
Add Diagnostics

### ISSUE THREAD

**Issue by ipa-cmh** [ros-industrial/ros2_canopen#104]
Either each driver node or the device container should publish diagnostic_msgs. These should at least indicate the state of each device (nmt, cia402, ...).

**Comment by ipa-vsp** [comment]
Added diagnostic messages for the `Proxy` and `cia402` drivers in PR #117. Also utilized a diagnostics aggregator to analyze the state of the device.

Example message data: 
- Proxy driver:
```yml
header:
  stamp:
    sec: 1684321506
    nanosec: 189701989
  frame_id: ''
status:
- level: "\0"                                             # 0: OK | 1: WARN | 2: ERROR | 3: STALE
  name: proxy_device_1
  message: 'Device is in operational state.'
  hardware_id: '2'                                   # Node ID
  values:                                                 # Key values recorder while the device is running 
  - key: Add to master
    value: OK
  - key: NMT
    value: START
  - key: EMCY
    value: 'Emergency message received. eec: 4369 er: 17 msef: 17 0 0 0 0 '
  - key: NMT
    value: START
```
- CiA402 driver:
```yml
header:
  stamp:
    sec: 1684486270
    nanosec: 689278892
  frame_id: ''
status:
- level: "\0"
  name: cia402_device_1
  message: Operation enabled
  hardware_id: '2'
  values:
  - key: Add to master
    value: OK
  - key: CiA402
    value: 'State transition: 2 -> 3'
  - key: CiA402
    value: 'State transition: 3 -> 4'
  - key: CiA402
    value: 'State transition: 4 -> 5'
  - key: CiA402
    value: 'Mode selected: 6'
  - key: CiA402
    value: 'No mode selected: 0'
  - key: CiA402
    value: 'Mode selected: 1'
```
![Screenshot from 2023-06-05 16-53-38](https://github.com/ros-industrial/ros2_canopen/assets/32260301/7eab4b80-0921-405b-b918-dbc57795a4d6)
