### ISSUE TITLE
Number of RPDO callback calls per mapped TPDO object

### ISSUE THREAD

**Issue by gsalinas** [ros-industrial/ros2_canopen#197]
Hi! Thanks once again for this package and all the assistance.

The proxy driver publishes one message to `proxy_device_1/rpdo` for each TPDO mapped object on the corresponding device, so for example, if my device has 4 TPDOs of 8 objects each, all of which transmit every sync period, then each sync period the proxy driver publishes to that topic 32 times. This happens regardless of, and as far as I can tell, without any awareness of, the TPDO numbering assigned in the bus.yml file (see an example of my situation below.)

I'm writing a custom device driver for a sensor, some of whose measurements are split across multiple objects in its object dictionary. If I extend the ProxyDriver class, is it possible to register an RPDO callback based on all 8 objects of TPDO 1 being available? The grouping of the TPDOs ensures that all the relevant objects are sampled synchronously on the device, which appears to be information that is discarded by then calling the RPDO callback 8 separate times.

Thank you so much!

```
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x2000, sub_index: 1}  
        - {index: 0x2000, sub_index: 2}  
        - {index: 0x2000, sub_index: 3}  
        - {index: 0x2000, sub_index: 4}  
        - {index: 0x2000, sub_index: 5}  
        - {index: 0x2000, sub_index: 6}  
        - {index: 0x2000, sub_index: 7}  
        - {index: 0x2000, sub_index: 8} 

    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x2000, sub_index: 9}  
        - {index: 0x2000, sub_index: 10} 
        - {index: 0x2000, sub_index: 11} 
        - {index: 0x2000, sub_index: 12} 
        - {index: 0x2000, sub_index: 13} 
        - {index: 0x2000, sub_index: 14} 
        - {index: 0x2000, sub_index: 15}
        - {index: 0x2000, sub_index: 16}
    3:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x2000, sub_index: 17} 
        - {index: 0x2000, sub_index: 18} 
        - {index: 0x2000, sub_index: 19} 
        - {index: 0x2000, sub_index: 20} 
        - {index: 0x2000, sub_index: 21} 
        - {index: 0x2000, sub_index: 22} 
        - {index: 0x2000, sub_index: 23} 
        - {index: 0x2000, sub_index: 24} 
    4:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x2000, sub_index: 25} 
        - {index: 0x2000, sub_index: 26} 
        - {index: 0x2000, sub_index: 27} 
        - {index: 0x2000, sub_index: 28} 
        - {index: 0x2000, sub_index: 29}  
        - {index: 0x2000, sub_index: 30}  
        - {index: 0x2000, sub_index: 31}  
        - {index: 0x2000, sub_index: 32} 
```

I'm implementing a custom device driver, and for my device, I'd like to
