### ISSUE TITLE
cogen_dcf causing build to fail

### ISSUE THREAD

**Issue by angstrem98** [ros-industrial/ros2_canopen#232]
I tried to implement a simple package, but I'm getting this error during the build:

`sed: can't read /home/dusan/ros2_ws/build/my_canopen_config/config/cia402/preprocessed_bus.yml: No such file or directory
gmake[2]: *** [CMakeFiles/cia402.dir/build.make:74: cia402] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:165: CMakeFiles/cia402.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2`

**Comment by ipa-cmh** [comment]
@angstrem98 can you provide the complete bus.yml?

**Comment by angstrem98** [comment]
```
options:
  dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 0
  package: "canopen_master_driver"
  driver: "ros2_canopen::MasterDriver"
  baudrate: 500
  sync_period: 10000    # us


defaults:
  dcf: "CDF3000.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  period: 10
  velocity_mode: 1
  revision_number: 0x00010000
  heartbeat_producer: 1000 # Heartbeat every 1000 ms
  scale_pos_to_dev : 1.0
  scale_vel_to_dev : 1.0
  scale_pos_from_dev : 1.0
  scale_vel_from_dev : 1.0
  sdo:
    - {index: 0x60C2, sub_index: 1, value: 50} # Set interpolation time for cyclic modes to 50 ms
    - {index: 0x60C2, sub_index: 2, value: -3} # Set base 10-3s
    - {index: 0x6081, sub_index: 0, value: 420}
    - {index: 0x6083, sub_index: 0, value: 800}
    - {index: 0x6060, sub_index: 0, value: 3} # 3 = profile velocity mode
  tpdo: # TPDO needed statusword, actual velocity, actual position, mode of operation
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6041, sub_index: 0} # status word
        - {index: 0x6061, sub_index: 0} # mode of operation display
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6064, sub_index: 0} # position actual value
        - {index: 0x606c, sub_index: 0} # velocity actual position
  rpdo: # RPDO needed controlword, target position, target velocity, mode of operation
    1:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x6040, sub_index: 0} # controlword
      - {index: 0x6060, sub_index: 0} # mode of operation
    2:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x60FF, sub_index: 0} # target velocity


nodes:
  joint1:
    node_id: 1
```
This builds on humble and iron.
Current error when launching:
```
[device_container_node-1] device_container_node: /home/dusan/iron_ws/build/lely_core_libraries/upstream/src/co/dev.c:710: co_dev_read_dcf: Assertion `dev' failed.
```
I'm sure that my physical CAN network is ok, because I was able to read out some data from drive using SDOs through a python library. Note that I'm trying to do 402 velocity control.
