### ISSUE TITLE
maxon EPOS4 Cia402Driver homing fails

### ISSUE THREAD

**Issue by leonce-m** [ros-industrial/ros2_canopen#236]
**Describe the bug**
When calling the /init service with homing mode 37 I get an error, but I'm still able to switch to position mode and control the motor.

**Logs**
```
[INFO] [launch]: All log files can be found below /home/admin/.ros/log/2023-12-12-17-56-19-432204-jetson-91204
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [launch.user]: /workspaces/isaac_ros-dev/install/srd_canopen/share/srd_canopen/config/as_can/bus.yml
[INFO] [launch.user]: /workspaces/isaac_ros-dev/install/srd_canopen/share/srd_canopen/config/as_can/master.dcf
[INFO] [launch.user]: /workspaces/isaac_ros-dev/install/srd_canopen/share/srd_canopen/config/as_can/master.bin
[INFO] [launch.user]: vcan1
[INFO] [device_container_node-1]: process started with pid [91222]
[device_container_node-1] [INFO] [1702400179.799718590] [device_container_node]: Starting Device Container with:
[device_container_node-1] [INFO] [1702400179.800007938] [device_container_node]: 	 master_config /workspaces/isaac_ros-dev/install/srd_canopen/share/srd_canopen/config/as_can/master.dcf
[device_container_node-1] [INFO] [1702400179.800033058] [device_container_node]: 	 bus_config /workspaces/isaac_ros-dev/install/srd_canopen/share/srd_canopen/config/as_can/bus.yml
[device_container_node-1] [INFO] [1702400179.800045378] [device_container_node]: 	 can_interface_name vcan1
[device_container_node-1] [INFO] [1702400179.801109264] [device_container_node]: Loading Master Configuration.
[device_container_node-1] [INFO] [1702400179.801847193] [device_container_node]: Load Library: /workspaces/isaac_ros-dev/install/canopen_master_driver/lib/libmaster_driver.so
[device_container_node-1] [INFO] [1702400179.806102766] [device_container_node]: Found class: rclcpp_components::NodeFactoryTemplate<ros2_canopen::MasterDriver>
[device_container_node-1] [INFO] [1702400179.806166735] [device_container_node]: Instantiate class: rclcpp_components::NodeFactoryTemplate<ros2_canopen::MasterDriver>
[device_container_node-1] [INFO] [1702400179.811619347] [master]: NodeCanopenBasicMaster
[device_container_node-1] [INFO] [1702400179.811870070] [device_container_node]: Load master component.
[device_container_node-1] [INFO] [1702400179.811997048] [device_container_node]: Added /master to executor
[device_container_node-1] [INFO] [1702400179.833326562] [device_container_node]: Loading Driver Configuration.
[device_container_node-1] [INFO] [1702400179.833512580] [device_container_node]: Found device steering_motor with driver ros2_canopen::Cia402Driver
[device_container_node-1] [INFO] [1702400179.833959338] [device_container_node]: Load Library: /workspaces/isaac_ros-dev/install/canopen_402_driver/lib/libcia402_driver.so
[device_container_node-1] [INFO] [1702400179.844284747] [device_container_node]: Found class: rclcpp_components::NodeFactoryTemplate<ros2_canopen::Cia402Driver>
[device_container_node-1] [INFO] [1702400179.844367468] [device_container_node]: Instantiate class: rclcpp_components::NodeFactoryTemplate<ros2_canopen::Cia402Driver>
[device_container_node-1] [INFO] [1702400179.850873629] [device_container_node]: Load driver component.
[device_container_node-1] [INFO] [1702400179.851085984] [device_container_node]: Added /steering_motor to executor
[device_container_node-1] [ERROR] [1702400179.873396503] [steering_motor]: Could not read enable diagnostics from config, setting to false.
[device_container_node-1] [INFO] [1702400179.873819932] [steering_motor]: scale_pos_to_dev_ 367.891156
[device_container_node-1] scale_pos_from_dev_ 0.002718
[device_container_node-1] scale_vel_to_dev_ 367.891156
[device_container_node-1] scale_vel_from_dev_ 0.002718
[device_container_node-1] 
[device_container_node-1] [INFO] [1702400179.876090328] [steering_motor]: eds file /workspaces/isaac_ros-dev/install/srd_canopen/share/srd_canopen/config/as_can/epos4.dcf
[device_container_node-1] [INFO] [1702400179.876133657] [steering_motor]: bin file /workspaces/isaac_ros-dev/install/srd_canopen/share/srd_canopen/config/as_can/steering_motor.bin
[device_container_node-1] Found rpdo mapped object: index=6040 subindex=0
[device_container_node-1] Found rpdo mapped object: index=6040 subindex=0
[device_container_node-1] Found rpdo mapped object: index=6060 subindex=0
[device_container_node-1] Found rpdo mapped object: index=6040 subindex=0
[device_container_node-1] Found rpdo mapped object: index=607a subindex=0
[device_container_node-1] Found rpdo mapped object: index=6040 subindex=0
[device_container_node-1] Found rpdo mapped object: index=60ff subindex=0
[device_container_node-1] Found tpdo mapped object: index=6041 subindex=0
[device_container_node-1] Found tpdo mapped object: index=6041 subindex=0
[device_container_node-1] Found tpdo mapped object: index=6061 subindex=0
[device_container_node-1] Found tpdo mapped object: index=6041 subindex=0
[device_container_node-1] Found tpdo mapped object: index=6064 subindex=0
[device_container_node-1] Found tpdo mapped object: index=6041 subindex=0
[device_container_node-1] Found tpdo mapped object: index=606c subindex=0
[device_container_node-1] [WARN] [1702400179.884073468] [steering_motor]: Wait for device to boot.
[device_container_node-1] [INFO] [1702400179.933429093] [steering_motor]: Driver booted and ready.
[device_container_node-1] [INFO] [1702400179.934314544] [steering_motor]: Starting with event mode.
[device_container_node-1] [INFO] [1702400179.938836200] [canopen_402_driver]: Fault reset
[device_container_node-1] [INFO] [1702400180.033997709] [steering_motor]: Slave 0xC: Switched NMT state to START
[device_container_node-1] [INFO] [1702400186.662334256] [canopen_402_driver]: Init: Read State
[device_container_node-1] [INFO] [1702400186.662485554] [canopen_402_driver]: Init: Enable
[device_container_node-1] [INFO] [1702400186.667502993] [canopen_402_driver]: Fault reset
[device_container_node-1] [INFO] [1702400186.768836386] [canopen_402_driver]: Init: Switch to homing
[device_container_node-1] [INFO] [1702400186.769709229] [canopen_402_driver]: Init: Execute homing
[device_container_node-1] homing did not start
[device_container_node-1] Homing failed
```

**Setup:**
 - Device: Jetson AGX Orin
 - OS: Jetpack 5.1.2-b104
 - ROS-Distro: humble
 - Branch/Commit: humble

**Additional context**
bus.yml
```
options:
  dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 1
  driver: ros2_canopen::MasterDriver
  package: canopen_master_driver
  baudrate: 1000
  # heartbeat_multiplier: 1
  # heartbeat_consumer: true
  # heartbeat_producer: 100
  # emcy_inhibit_time: 0
  sync_period: 10000
  # sync_window: 0
  # sync_overflow: 0
  # error_behavior: {1: 0x00}
  # nmt_inhibit_time: 0
  # start: true
  # start_nodes: true
  # start_all_nodes: false
  # reset_all_nodes: false
  # stop_all_nodes: false
  # boot_time: 500

nodes:
  steering_motor:
    node_id: 12
    driver: ros2_canopen::Cia402Driver
    package: canopen_402_driver
    dcf: epos4.dcf
    # heartbeat_multiplier: 1
    # heartbeat_consumer: false
    # heartbeat_producer: 0
    # error_behavior: {}
    # boot: true
    # mandatory: false
    # reset_communication: true
    polling: false # Enables polling of the drive status. If true, period will be used to run a ros2 timer as update loop. If false, the update loop will be triggered by the sync signal and directly executed in the canopen realtime loop.
    period: 10
    # switching_state: 1
    scale_pos_to_dev: 367.891156463
    scale_pos_from_dev: 0.00271819526
    scale_vel_to_dev: 367.891156463
    scale_vel_from_dev: 0.00271819526
    position_mode: 1
    # velocity_mode: 0
    # torque_mode: 0
    sdo:        
      - {index: 0x6081, sub_index: 0, value: 10000} # Set velocity
      - {index: 0x6083, sub_index: 0, value: 200000} # Set acceleration
      - {index: 0x6083, sub_index: 0, value: 200000} # Set deceleration
      - {index: 0x6085, sub_index: 0, value: 200000} # Set quickstop deceleration
      - {index: 0x6098, sub_index: 0, value: 37} # Set default homing mode to 37
```
