### ISSUE TITLE
Kinco device stuck at "Wait for devie to boot" when using real CAN Bus

### ISSUE THREAD

**Issue by glaciercoder** [ros-industrial/ros2_canopen#271]
**Describe the bug**
I'm using Kinco driver with ros2 canopen robot controller, when I launch the launch file, the process stuck in "Wait for device to boot" and I see no can messages using candump. I've made sure my can interface works fine.

Bus config:
```yaml
options:
  dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 255
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  baud_rate: 500
  heartbeat_consumer: false
  heartbeat_producer: 2000
  start_nodes: true
  sync_period: 5000000 

defaults:
  dcf: "kinco.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  period: 20
  velocity_mode: 1
  revision_number: 2
  polling: false
  heartbeat_producer: 1000
  sdo:
    - {index: 0x6060, sub_index: 0, value: 3} # Working mode
  tpdo: # TPDO needed statusword, actual velocity, actual position, mode of operation
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6041, sub_index: 0} # status word
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x606C, sub_index: 0} # position actual value
  rpdo: # RPDO needed controlword, target position, target velocity, mode of operation
    1:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x6040, sub_index: 0} # controlword
      - {index: 0x6060, sub_index: 0} # mode of operation
    2:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x60FF, sub_index: 0} # target velocity

nodes:
    wheel0_driving:
      node_id: 0x11
    wheel1_driving:
      node_id: 0x12
    wheel2_driving:
      node_id: 0x13
    wheel3_driving:
      node_id: 0x14
    wheel4_driving:
      node_id: 0x15
    wheel5_driving:
      node_id: 0x16
```
controller config:
```yaml
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController



forward_position_controller:
  ros__parameters:
    joints:
      - wheel0_steering
      - wheel1_steering
      - wheel2_steering
      - wheel3_steering
      - wheel4_steering
      - wheel5_steering
    interface_name: position 
    
forward_velocity_controller:
  ros__parameters:
    joints:
      - wheel0_driving
      - wheel1_driving
      - wheel2_driving
      - wheel3_driving
      - wheel4_driving
      - wheel5_driving
    interface_name: velocity
```

Launch file
```python
def generate_launch_description():
    robot_description_content = Command(
        [
            PathJoinSubstitution([FindExecutable(name="xacro")]),
            " ",
            PathJoinSubstitution(
                [
                    FindPackageShare("vos_description"),
                    "src",
                    "description",
                    "vos_bringup.urdf.xacro",
                ]
            ),
        ]
    )

    robot_control_config = PathJoinSubstitution(
        [FindPackageShare("kinco_interface"), "config", "forward_controller.yaml"]
    )

    control_node = Node(
        package="controller_manager",
        executable="ros2_control_node",
        parameters=[{"robot_description": robot_description_content}, 
                    robot_control_config],
        output="screen",
    )

    joint_state_broadcaster_spawner = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["joint_state_broadcaster", "--controller-manager", "/controller_manager"],
    )

    forward_position_controller_spawner = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["forward_position_controller", "--controller-manager", "/controller_manager"],
    )

    forward_velocity_controller_spawner = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["forward_velocity_controller", "--controller-manager", "/controller_manager"],
    )

    robot_state_publisher_node = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        output="both",
        parameters=[{"robot_description": robot_description_content}],
    )

    nodes_to_start = [
        robot_state_publisher_node,
        control_node,
        joint_state_broadcaster_spawner,
        forward_position_controller_spawner,
        forward_velocity_controller_spawner,
    ]

    return LaunchDescription(nodes_to_start)
```

When it stuck at "Wait for device ", I see no messages such as "[INFO] [launch.user]: node 'basic_slave_node' reached the 'inactive' state, 'activating'.
[basic_slave_node-1] [INFO] [1710791762.023111597] [can0_com_node]: Reaching inactive state.
[basic_slave_node-1] [INFO] [1710791762.024751476] [can0_com_node]: Reaching active state.
[basic_slave_node-1] [INFO] [1710791762.026134468] [can0_com_node]: Created slave for node_id 6." mentioned by https://github.com/ros-industrial/ros2_canopen/issues/269#issue-2195244670. 
However, when I call 
```shell
ros2 service call /cia402_device_2/init std_srvs/srv/Trigger
```
It said "The device is  no activated" and returned False.

**Setup:**
 - Device:
 - OS: Ubuntu 22.04
 - ROS-Distro: Humble
 - Branch/Commit: Humble

**Additional context**
I'm on an urgent project, great appreciations if someone could help me.
