### ISSUE TITLE
N5-2-2 motor controller timed out

### ISSUE THREAD

**Issue by javijurado** [ros-industrial/ros2_canopen#356]
**Describe the bug**
I'm trying to communicate with a N5-2-2 motor controller designed by Nanotec, but when I launch my master ant the driver for the motor controller I got an timed out
**Logs**
Output from the terminal:
```bash
ros2 launch app manager.launch.py 
[INFO] [launch]: All log files can be found below /home/intermodalics/.ros/log/2025-05-22-14-48-13-203659-im-laptop-016-1527
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [launch.user]: Launching canopen_core with output=screen
[INFO] [launch.user]: /home/javier/workspace/BPPAS/bppas-cleaning/install/share/can_manager/config/bus.yml
[INFO] [launch.user]: /home/javier/workspace/BPPAS/bppas-cleaning/install/share/can_manager/config/master.dcf
[INFO] [launch.user]: 
[INFO] [launch.user]: can0
[INFO] [device_container_node-1]: process started with pid [1543]
[device_container_node-1] [INFO] [1747918093.357806350] [device_container_node]: Starting Device Container with:
[device_container_node-1] [INFO] [1747918093.357886256] [device_container_node]:         master_config /home/javier/workspace/BPPAS/bppas-cleaning/install/share/can_manager/config/master.dcf
[device_container_node-1] [INFO] [1747918093.357896423] [device_container_node]:         bus_config /home/javier/workspace/BPPAS/bppas-cleaning/install/share/can_manager/config/bus.yml
[device_container_node-1] [INFO] [1747918093.357903036] [device_container_node]:         can_interface_name can0
[device_container_node-1] [INFO] [1747918093.358392610] [device_container_node]: Loading Master Configuration.
[device_container_node-1] [INFO] [1747918093.358636004] [device_container_node]: Load Library: /opt/ros/jazzy/lib/libmaster_driver.so
[device_container_node-1] [INFO] [1747918093.359986877] [device_container_node]: Found class: rclcpp_components::NodeFactoryTemplate<ros2_canopen::MasterDriver>
[device_container_node-1] [INFO] [1747918093.360005237] [device_container_node]: Instantiate class: rclcpp_components::NodeFactoryTemplate<ros2_canopen::MasterDriver>
[device_container_node-1] [INFO] [1747918093.362511094] [master]: NodeCanopenBasicMaster
[device_container_node-1] [INFO] [1747918093.362522158] [device_container_node]: Load master component.
[device_container_node-1] [INFO] [1747918093.362528270] [device_container_node]: Added /master to executor
[device_container_node-1] [WARN] [1747918093.363013869] [master]: No timeout parameter found in config file. Using default value of 100ms.
[device_container_node-1] [INFO] [1747918093.363026136] [master]: Master boot timeout set to 2000ms.
[device_container_node-1] [INFO] [1747918093.370003298] [device_container_node]: Loading Driver Configuration.
[device_container_node-1] [INFO] [1747918093.370017545] [device_container_node]: Found device left_motor with driver ros2_canopen::Cia402Driver
[device_container_node-1] [INFO] [1747918093.370168344] [device_container_node]: Load Library: /home/javier/workspace/BPPAS/bppas-cleaning/install/lib/libcia402_driver.so
[device_container_node-1] [INFO] [1747918093.373300605] [device_container_node]: Found class: rclcpp_components::NodeFactoryTemplate<ros2_canopen::Cia402Driver>
[device_container_node-1] [INFO] [1747918093.373325414] [device_container_node]: Instantiate class: rclcpp_components::NodeFactoryTemplate<ros2_canopen::Cia402Driver>
[device_container_node-1] [INFO] [1747918093.376024774] [device_container_node]: Load driver component.
[device_container_node-1] [INFO] [1747918093.376052070] [device_container_node]: Added /left_motor to executor
[device_container_node-1] [INFO] [1747918093.382474645] [left_motor]: Non transmit timeout100ms
[device_container_node-1] [WARN] [1747918093.382560009] [left_motor]: Could not read enable diagnostics from config, setting to false.
[device_container_node-1] [INFO] [1747918093.382727946] [left_motor]: scale_pos_to_dev_ 1000.000000
[device_container_node-1] scale_pos_from_dev_ 0.001000
[device_container_node-1] scale_vel_to_dev_ 1000.000000
[device_container_node-1] scale_vel_from_dev_ 0.001000
[device_container_node-1] offset_pos_to_dev_ 0.000000
[device_container_node-1] offset_pos_from_dev_ 0.000000
[device_container_node-1] homing_timeout_seconds_ 10
[device_container_node-1] Found rpdo mapped object: index=6040 subindex=0
[device_container_node-1] Found rpdo mapped object: index=6060 subindex=0
[device_container_node-1] Found rpdo mapped object: index=3202 subindex=0
[device_container_node-1] Found rpdo mapped object: index=607a subindex=0
[device_container_node-1] Found rpdo mapped object: index=6081 subindex=0
[device_container_node-1] Found rpdo mapped object: index=6042 subindex=0
[device_container_node-1] Found rpdo mapped object: index=60fe subindex=1
[device_container_node-1] Found tpdo mapped object: index=6041 subindex=0
[device_container_node-1] Found tpdo mapped object: index=6061 subindex=0
[device_container_node-1] Found tpdo mapped object: index=6064 subindex=0
[device_container_node-1] Found tpdo mapped object: index=6044 subindex=0
[device_container_node-1] Found tpdo mapped object: index=60fd subindex=0
[device_container_node-1] [INFO] [1747918093.390671530] [left_motor]: Hey8 
[device_container_node-1] [INFO] [1747918093.390708568] [left_motor]: Hey5 
[device_container_node-1] [INFO] [1747918093.390746267] [left_motor]: Hey6 
[device_container_node-1] [INFO] [1747918093.390750010] [left_motor]: Hey7 
[device_container_node-1] [WARN] [1747918093.390758191] [left_motor]: Wait for device to boot.
[device_container_node-1] [INFO] [1747918093.390828463] [left_motor]: Driver booted and ready.
[device_container_node-1] [INFO] [1747918093.391053139] [left_motor]: Starting with event mode.
[device_container_node-1] [INFO] [1747918093.426445792] [left_motor]: Slave 0x1: Switched NMT state to START
[device_container_node-1] [INFO] [1747918093.669614870] [canopen_402_driver]: Fault reset
[device_container_node-1] sync_sdo_read_typed: id=1 index=0x606c subindex=0 timed out.
```

candump logs
```bash
  can0  703   [1]  00
  can0  000   [2]  82 00
  can0  701   [1]  00
  can0  601   [8]  40 00 10 00 00 00 00 00
  can0  581   [8]  43 00 10 00 92 01 06 00
  can0  601   [8]  40 18 10 01 00 00 00 00
  can0  581   [8]  43 18 10 01 6C 02 00 00
  can0  601   [8]  40 18 10 02 00 00 00 00
  can0  581   [8]  43 18 10 02 0A 00 00 00
  can0  000   [2]  01 01
  can0  701   [1]  05
  can0  181   [3]  40 06 02
  can0  281   [4]  00 00 00 00
  can0  381   [2]  00 00
  can0  481   [4]  00 00 00 00
  can0  080   [0] 
  can0  201   [7]  37 2F 00 00 00 00 00    <---- Message appears after  [device_container_node-1] sync_sdo_read_typed: id=1 index=0x606c subindex=0 timed out.
```

My files are:
bus.yml
```yaml
options:
  dcf_path:  "@BUS_CONFIG_PATH@"

master:
  node_id: 3
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  sync_period: 20000
  bitrate: 1000000

left_motor:
  node_id: 1
  dcf: "N5-2-2.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  polling: false
  heartbeat_producer: 1000 # Heartbeat every 1000 ms
  sdo: # SDO executed during config
    # Pole pair count (example: 50 pole pairs for a 1.8° stepper motor)
    - {index: 0x2030, sub_index: 0, value: 50}      # Motor pole pair count

    # BLDC motor
    - {index: 0x2031, sub_index: 0, value: 20000}    # Peak current in mA
    - {index: 0x203B, sub_index: 1, value: 6900}    # Rated current in mA
    - {index: 0x203B, sub_index: 2, value: 100}     # Max peak current duration in ms
    # - {index: 0x3202, sub_index: 0, value: 0x00000041} # Motor type: BLDC

    # Encoder configuration
    - {index: 0x2059, sub_index: 0, value: 0x00000000} # Encoder: 5V single-ended

    - {index: 0x6040, sub_index: 0, value: 0x80}  # Fault reset
    - {index: 0x6040, sub_index: 0, value: 0x06}  # Shutdown
    - {index: 0x6040, sub_index: 0, value: 0x07}  # Switch on
    - {index: 0x6060, sub_index: 0, value: 2}  # Set operation mode to Velocity Position
    - {index: 0x6040, sub_index: 0, value: 0x0F}  # Enable operation
  tpdo: # TPDO needed statusword, actual velocity, actual position, mode of operation
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6041, sub_index: 0} # status word
        - {index: 0x6061, sub_index: 0} # mode of operation display
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6064, sub_index: 0} # position actual value
        - {index: 0x606c, sub_index: 0} # velocity actual position
    3:
      enabled: false
    4:
      enabled: false
  rpdo: # RPDO needed controlword, target position, target velocity, mode of operation
    1:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x6040, sub_index: 0} # controlword
      - {index: 0x6060, sub_index: 0} # mode of operation
    2:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x607A, sub_index: 0} # target position
      - {index: 0x60FF, sub_index: 0} # target velocity

# nodes:  <--- This is not working for me but not for this ticket
#   left_motor:
#     node_id: 1

```

Launch file
```python
from launch import LaunchDescription
from launch.substitutions import PathJoinSubstitution, LaunchConfiguration
from launch.actions import DeclareLaunchArgument, OpaqueFunction, IncludeLaunchDescription, LogInfo
from launch.launch_description_sources import PythonLaunchDescriptionSource

from launch_ros.substitutions import FindPackageShare

import yaml

def launch_setup(context, *args, **kwargs):

    nodes_to_start = []

    # Launch master node

    master_launch = PathJoinSubstitution(
        [FindPackageShare("canopen_core"), "launch", "canopen.launch.py"]
    )

    master_config = PathJoinSubstitution(
        [FindPackageShare("can_manager"), "config", "master.dcf"]
    )

    bus_config = PathJoinSubstitution(
        [FindPackageShare("can_manager"), "config", "bus.yml"]
    )
    
    # Optional log to confirm the inclusion step
    nodes_to_start.append(
        LogInfo(msg="Launching canopen_core with output=screen")
    )

    nodes_to_start.append(
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(master_launch),
            launch_arguments={
                "master_config": master_config,
                "master_bin": "",
                "bus_config": bus_config,
                "can_interface_name": "can0",
                "output": "screen",  # Add this in case the included file reads it as an argument
            }.items(),
        )
    )

    return nodes_to_start

def generate_launch_description():
    declared_arguments = []

    declared_arguments.append(
        DeclareLaunchArgument(
            "can_interface_name",
            default_value="vcan0",
            description="CAN interface name to run the master and, when in simulation, the fake slaves.",
        )
    )
    
    return LaunchDescription(declared_arguments + [OpaqueFunction(function=launch_setup)])

```

**Setup:**
 - Device:
 - OS: Linux
 - ROS-Distro: Jazzy
 - Branch/Commit:

**Additional context**
