### ISSUE TITLE
RPDO2 published at a lower frequency than configured

### ISSUE THREAD

**Issue by Alexisbol** [ros-industrial/ros2_canopen#357]
**Describe the bug**
RPDO2 is running 33.33Hz of the expected 100 Hz.
I'm trying to control 6 motors with 6 Lexium 32A drives using ros2_canopen at 100 Hz.
My controller manager and the CAN bus are both running at 100 Hz.
I created a node that publishes joint position commands at 100 Hz.
However, when I inspect the CAN bus using candump, I see that RPDO2 (responsible for the target position) is only transmitting at 33.33 Hz.
The other PDOs (TPDO1, TPDO2, and RPDO1) are operating at 100 Hz.

**Logs**
Configuration files :
```yaml
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz 
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    position_controller:
      type: position_controllers/JointGroupPositionController

position_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    action_monitor_rate: 20.0
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
```
```yaml
options:
  dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 10
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  sync_period: 10000 #micro s

defaults:
  dcf: "SELXM32A_0126E.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  mandatory: true
  boot: true
  reset_communication: true
  # CIA402 driver specific params
  period: 10 #ms
  heartbeat_producer: 1000 #ms
  switching_state: 3
  position_mode: 1
  velocity_mode: 3
  scale_pos_to_dev: 117342
  scale_pos_from_dev: 0.00000852212

  # SDO for init config
  sdo:
  - {index: 0x6098, sub_index: 0, value: 35} # homing to actual pos = 0
  - {index: 0x6081, sub_index: 0, value: 1000} # velocity for profile position
  #- {index: 0x607A, sub_index: 0, value: 0} # target pos 0  
  - {index: 0x6060, sub_index: 0, value: 1} # mode of operation 3 = profile vel, 1 = profile pos
  - {index: 0x6083, sub_index: 0, value: 3000} # acceleration of the motion profile for velocity
  - {index: 0x6084, sub_index: 0, value: 3000} # deceleration of the motion profile for velocity
  - {index: 0x607F, sub_index: 0, value: 2320} # deceleration of the motion profile for velocity

  #PDOS
  tpdo: # TPDO needed statusword, actual velocity, actual position, mode of operation
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6041, sub_index: 0} # status word
        - {index: 0x6061, sub_index: 0} # mode of operation display
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6064, sub_index: 0} # position actual value
        - {index: 0x606c, sub_index: 0} # velocity actual value
  rpdo: # RPDO needed controlword, target position, target velocity, mode of operation
    1:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x6040, sub_index: 0} # controlword
      - {index: 0x6060, sub_index: 0} # mode of operation
    2:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x60FF, sub_index: 0} # target vel
      # For position control we need to send the target position
      - {index: 0x607A, sub_index: 0} # target position

    # 3:
    #   enabled: true
    #   cob_id: "auto"
    #   mapping:
    #   - {index: 0x6060, sub_index: 0} # mode of operation

nodes:
  joint_1:
    node_id: 6

  joint_2:
    node_id: 3

  joint_3:
    node_id: 1

  joint_4:
    node_id: 2

  joint_5:
    node_id: 5

  joint_6:
    node_id: 4
```

Results from experiments : 
Observation of RPDO2 for motor 6 (joint_1) using
```bash
candump can0 -ta | grep -E "can0  306" 
```
Messages are received at 33Hz
```
 (1747995078.000743)  can0  306   [8]  00 00 00 00 B4 CE 1F 00
 (1747995078.030826)  can0  306   [8]  00 00 00 00 14 D0 1F 00
 (1747995078.060766)  can0  306   [8]  00 00 00 00 75 D1 1F 00
 (1747995078.090853)  can0  306   [8]  00 00 00 00 D5 D2 1F 00
 (1747995078.120943)  can0  306   [8]  00 00 00 00 35 D4 1F 00
 (1747995078.150903)  can0  306   [8]  00 00 00 00 95 D5 1F 00
 (1747995078.180614)  can0  306   [8]  00 00 00 00 F5 D6 1F 00
 (1747995078.210762)  can0  306   [8]  00 00 00 00 55 D8 1F 00
 (1747995078.240678)  can0  306   [8]  00 00 00 00 B5 D9 1F 00
 (1747995078.270499)  can0  306   [8]  00 00 00 00 15 DB 1F 00
 (1747995078.300826)  can0  306   [8]  00 00 00 00 75 DC 1F 00
 (1747995078.330829)  can0  306   [8]  00 00 00 00 D5 DD 1F 00
 (1747995078.360742)  can0  306   [8]  00 00 00 00 35 DF 1F 00
 (1747995078.390706)  can0  306   [8]  00 00 00 00 95 E0 1F 00
 (1747995078.420764)  can0  306   [8]  00 00 00 00 F5 E1 1F 00
 (1747995078.450979)  can0  306   [8]  00 00 00 00 55 E3 1F 00
 (1747995078.481076)  can0  306   [8]  00 00 00 00 B5 E4 1F 00
 (1747995078.510730)  can0  306   [8]  00 00 00 00 15 E6 1F 00
 (1747995078.540533)  can0  306   [8]  00 00 00 00 75 E7 1F 00
 (1747995078.570626)  can0  306   [8]  00 00 00 00 D5 E8 1F 00
 (1747995078.600812)  can0  306   [8]  00 00 00 00 35 EA 1F 00
 (1747995078.630850)  can0  306   [8]  00 00 00 00 95 EB 1F 00
 (1747995078.660668)  can0  306   [8]  00 00 00 00 F5 EC 1F 00
 (1747995078.690948)  can0  306   [8]  00 00 00 00 55 EE 1F 00
 (1747995078.720878)  can0  306   [8]  00 00 00 00 B5 EF 1F 00
 (1747995078.751005)  can0  306   [8]  00 00 00 00 15 F1 1F 00
 (1747995078.780653)  can0  306   [8]  00 00 00 00 75 F2 1F 00
 (1747995078.810619)  can0  306   [8]  00 00 00 00 D5 F3 1F 00
 (1747995078.840849)  can0  306   [8]  00 00 00 00 35 F5 1F 00
 (1747995078.870875)  can0  306   [8]  00 00 00 00 95 F6 1F 00
 (1747995078.900487)  can0  306   [8]  00 00 00 00 F5 F7 1F 00
 (1747995078.930738)  can0  306   [8]  00 00 00 00 55 F9 1F 00
 (1747995078.960508)  can0  306   [8]  00 00 00 00 B5 FA 1F 00
 (1747995078.990653)  can0  306   [8]  00 00 00 00 15 FC 1F 00

```
Message publish at 100Hz on /position_controller/commands
```
[INFO] [1747995078.007820672] [joint_position_publisher]: Publishing: array('d', [3.189, 3.189, 3.189, 3.189, 3.189, 3.189])
[INFO] [1747995078.017654073] [joint_position_publisher]: Publishing: array('d', [3.19, 3.19, 3.19, 3.19, 3.19, 3.19])
[INFO] [1747995078.027541471] [joint_position_publisher]: Publishing: array('d', [3.191, 3.191, 3.191, 3.191, 3.191, 3.191])
[INFO] [1747995078.038113418] [joint_position_publisher]: Publishing: array('d', [3.192, 3.192, 3.192, 3.192, 3.192, 3.192])
[INFO] [1747995078.048180572] [joint_position_publisher]: Publishing: array('d', [3.193, 3.193, 3.193, 3.193, 3.193, 3.193])
[INFO] [1747995078.057389287] [joint_position_publisher]: Publishing: array('d', [3.194, 3.194, 3.194, 3.194, 3.194, 3.194])
```
**Setup:**
 - Device: Lexium 32A Servo Drive 
 - OS: Ubuntu 22.04
 - ROS-Distro: Humble
 - Branch/Commit: Humble

**Additional context**
I tried the same setup with the joint_trajectory_controller but the issue persists.
Ultimately, I want to use interpolated position mode for smooth motion. However, for that to work properly, I need to control the communication frequency on the CAN bus.
