### ISSUE TITLE
Could not create object of class type cia402_robot_controller::Cia402DeviceController

### ISSUE THREAD

**Issue by javijurado** [ros-industrial/ros2_canopen#358]
**Describe the bug**
As a background. I'm trying to control a mecanum robot using a joystick. ros_control works and ros2_canopen works. The only thing that is missing the bridge between ros2_canopen and ros_control. That is why I use your driver Cia402RobotController but when I launch the controller Cia402RobotController it triggers the following error

```bash
Could not create object of class type cia402_robot_controller::Cia402DeviceController as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[spawner-9] [FATAL] [1748424692.771802965] [spawner_robot_controller]: Failed loading controller robot_controller
```

**To Reproduce**
launch.py
```py
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.actions import RegisterEventHandler
from launch.event_handlers import OnProcessExit
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command, FindExecutable, LaunchConfiguration, PathJoinSubstitution

from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


import os


def generate_launch_description():

    use_sim_time = LaunchConfiguration('use_sim_time', default=True)


    # Joy controller
    joystick_params = PathJoinSubstitution([
        FindPackageShare('app'),
        'config',
        'joystick_params.yaml'
    ])
    
    joy_controller = Node(
        package="joy",
        executable="joy_node",
        name="joy_node",
        parameters=[joystick_params]
    )

    # Teleop twist joy
    teleop_controller = Node(
        package="teleop_twist_joy",
        executable="teleop_node",
        name="teleop_node",
        parameters=[joystick_params]
    )

    # Get URDF via xacro
    robot_description_content = Command(
        [
            PathJoinSubstitution([FindExecutable(name='xacro')]),
            ' ',
            PathJoinSubstitution(
                [FindPackageShare('app'),
                 'urdf', 'mecanum_drive.xacro.urdf']
            ),
        ]
    )
    robot_description = {'robot_description': robot_description_content}
    robot_controllers = PathJoinSubstitution(
        [
            FindPackageShare('app'),
            'config',
            'mecanum_drive_controller.yaml',
        ]
    )

    node_robot_state_publisher = Node(
        package='robot_state_publisher',
        executable='robot_state_publisher',
        output='screen',
        parameters=[robot_description]
    )

    gz_spawn_entity = Node(
        package='ros_gz_sim',
        executable='create',
        output='screen',
        arguments=['-topic', 'robot_description',
                   '-name', 'mecanum_vehicle', '-allow_renaming', 'true'],
    )

    joint_state_broadcaster_spawner = Node(
        package='controller_manager',
        executable='spawner',
        arguments=['joint_state_broadcaster'],
    )

    robot_controller_spawner = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["robot_controller", "--controller-manager", "/controller_manager"],
    )
    
    mecanum_drive_controller_spawner = Node(
        package='controller_manager',
        executable='spawner',
        arguments=[
            'mecanum_drive_controller',
            '--param-file',
            robot_controllers,
        ],
    )

    # Bridge
    bridge = Node(
        package='ros_gz_bridge',
        executable='parameter_bridge',
        arguments=['/clock@rosgraph_msgs/msg/Clock[gz.msgs.Clock'],
        output='screen'
    )

    master_launch = PathJoinSubstitution(
        [FindPackageShare("canopen_core"), "launch", "canopen.launch.py"]
    )

    master_bin = PathJoinSubstitution(
        [FindPackageShare("can_manager"), "config", "master.bin"]
    )

    master_config = PathJoinSubstitution(
        [FindPackageShare("can_manager"), "config", "master.dcf"]
    )

    bus_config = PathJoinSubstitution(
        [FindPackageShare("can_manager"), "config", "bus.yml"]
    )

    can_master = IncludeLaunchDescription(
            PythonLaunchDescriptionSource(master_launch),
            launch_arguments={
                "master_config": master_config,
                "master_bin": master_bin,
                "bus_config": bus_config,
                "can_interface_name": "can0",
            }.items(),
        )

    return LaunchDescription([
        # Launch joy controller
        joy_controller,
        teleop_controller,
        # Launch gazebo environment
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                [PathJoinSubstitution([FindPackageShare('ros_gz_sim'),
                                       'launch',
                                       'gz_sim.launch.py'])]),
            launch_arguments=[('gz_args', [' -r -v 1 empty.sdf'])]),
        RegisterEventHandler(
            event_handler=OnProcessExit(
                target_action=gz_spawn_entity,
                on_exit=[joint_state_broadcaster_spawner],
            )
        ),
        RegisterEventHandler(
            event_handler=OnProcessExit(
                target_action=joint_state_broadcaster_spawner,
                on_exit=[robot_controller_spawner],
            )
        ),
        RegisterEventHandler(
            event_handler=OnProcessExit(
                target_action=joint_state_broadcaster_spawner,
                on_exit=[mecanum_drive_controller_spawner],
            )
        ),
        bridge,
        node_robot_state_publisher,
        gz_spawn_entity,
        #can_master,
        # Launch Arguments
        DeclareLaunchArgument(
            'use_sim_time',
            default_value=use_sim_time,
            description='If true, use simulated clock'),
    ])

```
mecanum_driver_controller.yaml

```yaml
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot_controller:
      type: canopen_ros2_controllers/Cia402RobotController

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

robot_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
    operation_mode: 1
    command_poll_freq: 5

mecanum_drive_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_right_wheel_joint
      - rear_left_wheel_joint
    reference_timeout: 1.0 # max time between command messages before the vehicle should stop
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"
    kinematics:
        base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
        wheels_radius: 0.3
        sum_of_robot_center_projection_on_X_Y_axis: 1.1
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true
    interface_name: position
```

**Expected behavior**

**Logs**

**Setup:**
 - Device: Ubuntu 24.04
 - OS:
 - ROS-Distro: Jazzy 
 - Branch/Commit: Master

Any advise why this is happening?

Since this PR (https://github.com/ros-industrial/ros2_canopen/pull/132), that driver has been removed
