### ISSUE TITLE
CAN frame: Operation canceled

### ISSUE THREAD

**Issue by jclinton830** [ros-industrial/ros2_canopen#93]
**Describe the bug**

After the node has been configured basic_slave node is reporting ` warning: error writing CAN frame: Operation canceled`

Do you have any idea what would be causing this issue? I have submitted the log after launching [proxy_lifecycle_setup.launch.py](http://proxy_lifecycle_setup.launch.py/)  and also the bus.yaml file

**Logs**

```
groundhog@groundhogPC:~/gh_ws$ ros2 launch groundhog_canopen [proxy_lifecycle_setup.launch.py](http://proxy_lifecycle_setup.launch.py/)
[INFO] [launch]: All log files can be found below /home/groundhog/.ros/log/2023-03-01-15-05-48-779937-groundhogPC-121543
[INFO] [launch]: Default logging verbosity is set to INFO
/home/groundhog/gh_ws/install/groundhog_canopen/share/groundhog_canopen/config/proxy_write_sdo/master.dcf
[INFO] [launch.user]: /home/groundhog/gh_ws/install/groundhog_canopen/share/groundhog_canopen/config/bus_two/bus.yml
[INFO] [launch.user]: /home/groundhog/gh_ws/install/groundhog_canopen/share/groundhog_canopen/config/bus_two/master.dcf
[INFO] [launch.user]:
[INFO] [launch.user]: can0
[INFO] [basic_slave_node-1]: process started with pid [121555]
[INFO] [device_container_node-2]: process started with pid [121557]
[device_container_node-2] [INFO] [1677643551.581533659] [device_container_node]: Starting Device Container with:
[device_container_node-2] [INFO] [1677643551.583381255] [device_container_node]:     master_config /home/groundhog/gh_ws/install/groundhog_canopen/share/groundhog_canopen/config/bus_two/master.dcf
[device_container_node-2] [INFO] [1677643551.584828511] [device_container_node]:     bus_config /home/groundhog/gh_ws/install/groundhog_canopen/share/groundhog_canopen/config/bus_two/bus.yml
[device_container_node-2] [INFO] [1677643551.586292279] [device_container_node]:     can_interface_name can0
[device_container_node-2] [INFO] [1677643551.594472759] [device_container_node]: Loading Master Configuration.
[device_container_node-2] [INFO] [1677643551.597940061] [device_container_node]: Load Library: /home/groundhog/gh_ws/install/canopen_master_driver/lib/liblifecycle_master_driver.so
[device_container_node-2] [INFO] [1677643551.631148562] [device_container_node]: Found class: rclcpp_components::NodeFactoryTemplate<ros2_canopen::LifecycleMasterDriver>
[device_container_node-2] [INFO] [1677643551.632752080] [device_container_node]: Instantiate class: rclcpp_components::NodeFactoryTemplate<ros2_canopen::LifecycleMasterDriver>
[device_container_node-2] [INFO] [1677643551.673329425] [master]: NodeCanopenBasicMaster
[device_container_node-2] [INFO] [1677643551.674027649] [device_container_node]: Load master component.
[device_container_node-2] [INFO] [1677643551.674263459] [device_container_node]: Added /master to executor
[device_container_node-2] [INFO] [1677643551.683782439] [device_container_node]: Loading Driver Configuration.
[device_container_node-2] [INFO] [1677643551.684021177] [device_container_node]: Found device hetronic_rc with driver ros2_canopen::LifecycleProxyDriver
[device_container_node-2] [INFO] [1677643551.685647591] [device_container_node]: Load Library: /home/groundhog/gh_ws/install/canopen_proxy_driver/lib/liblifecycle_proxy_driver.so
[INFO] [launch.user]: node 'basic_slave_node' reached the 'inactive' state, 'activating'.
[basic_slave_node-1] [INFO] [1677643551.692696231] [hetronic_can_node]: Reaching inactive state.
[device_container_node-2] [INFO] [1677643551.698330374] [device_container_node]: Found class: rclcpp_components::NodeFactoryTemplate<ros2_canopen::LifecycleProxyDriver>
[device_container_node-2] [INFO] [1677643551.698468120] [device_container_node]: Instantiate class: rclcpp_components::NodeFactoryTemplate<ros2_canopen::LifecycleProxyDriver>
[basic_slave_node-1] [INFO] [1677643551.714879490] [hetronic_can_node]: Reaching active state.
[device_container_node-2] [INFO] [1677643551.734151497] [device_container_node]: Load driver component.
[device_container_node-2] [INFO] [1677643551.734437094] [device_container_node]: Added /hetronic_rc to executor
[basic_slave_node-1] NMT: entering reset application state
[basic_slave_node-1] NMT: entering reset communication state
[basic_slave_node-1] NMT: running as slave
[basic_slave_node-1] NMT: entering pre-operational state
[basic_slave_node-1] NMT: entering operational state
[basic_slave_node-1] [INFO] [1677643551.755971389] [hetronic_can_node]: Created slave for node_id 100.
[device_container_node-2] [INFO] [1677643551.780409953] [device_container_node]: Loading Manager Configuration.
[device_container_node-2] [INFO] [1677643551.821794468] [device_container_node]: Added /lifecycle_manager to executor
[basic_slave_node-1] warning: error writing CAN frame: Operation canceled
```

Here is the bus.yaml

```
master:
  node_id: 1
  driver: ros2_canopen::LifecycleMasterDriver
  package: canopen_master_driver

hetronic_rc:
  node_id: 100
  dcf: "RX_ES-CAN-HL_line0.eds"
  dcf_path: "install/groundhog_canopen/share/groundhog_canopen/config/hetronic_rc"
  driver: "ros2_canopen::LifecycleProxyDriver"
  package: "canopen_proxy_driver"
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0xF
      event_timer: 50
      mapping:
        - {index: 0x5000, sub_index: 0}
        - {index: 0x5000, sub_index: 1}
        - {index: 0x5000, sub_index: 2}
        - {index: 0x5000, sub_index: 3}
        - {index: 0x5000, sub_index: 4}
        - {index: 0x5000, sub_index: 5}
        - {index: 0x5000, sub_index: 6}
        - {index: 0x5000, sub_index: 7}
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0xF
      event_timer: 50
      mapping:
        - {index: 0x5001, sub_index: 0}
        - {index: 0x5001, sub_index: 1}
        - {index: 0x5001, sub_index: 2}
        - {index: 0x5001, sub_index: 3}
        - {index: 0x5001, sub_index: 4}
        - {index: 0x5001, sub_index: 5}
        - {index: 0x5001, sub_index: 6}
        - {index: 0x5001, sub_index: 7}
    3:
      enabled: false
    4:
      enabled: false
```

**Setup:**
 - OS: Ubuntu 22.04
 - ROS-Distro: Humble
